# Project Codebook
This codebook describes the variables, data and transformations performed to clean up the data. 

## Variables
### Measurements
* `tBodyAccMeanX` ... `fBodyBodyGyroJerkMag-std()` 

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

mean(): Mean value
std(): Standard deviation


### Identifiers
* `subjects`: Nr of person that performed the experiment
* `activity`: One of the six performed activities, with the following labels:
** 1 - WALKING
** 2 - WALKING_UPSTAIRS
** 3 - WALKING_DOWNSTAIRS
** 4 - SITTING
** 5 - STANDING
** 6 - LAYING

## Data
Used the "Human Activity Recognition Using Smartphones Dataset" Version 1.0 available under https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

## Transformations
1. Merges training and test sets to create one dataset.
 `train/X_train.txt`: Training set. and `test/X_test.txt`: Test set.
2. Extracts only the measurements on the mean and standard deviation from mergedData.
 Keeping only variables with "-mean()" or "-st()" inside the name.
3. Uses descriptive activity names to name the activities in the data set
 `activity_labels.txt` is cbind with mergedData and activity numbers mutated into the labels
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
